# Site settings
title: Cryptocurrency and Artificial Intelligence Society
email: your-email@domain.com
description: >
   High impact, practical education in the most radical technological advances of our age - AI and Blockchain.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://cryptosoc.github.io # the base hostname & protocol for your site
git_address: https://github.com/CryptoSoc/website
git_edit_address: https://github.com/CryptoSoc/website/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
